version: '2'

services:
  db:
    image: mysql
    restart: always
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "assisticodb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
  adminer:
    image: adminer
    restart: always
    container_name: admin
    ports:
      - 8080:8080
volumes:
  db-data:
    driver: local

